apiVersion: v1
kind: Pod
metadata:
    name: grpc-server-pod
spec:
    containers:
    - name: grpc-server
      image: time-grpc-app:local
      workingDir: /app
      ports:
      - containerPort: 50051
      command:
      - python3
      - "time_server.py"
    restartPolicy: OnFailure

