apiVersion: v1
kind: Service
metadata:
  name: my-timesrv
spec:
  selector:
    name: timesrv-py-grpc
  ports: 
  - name: py-grpc
    port: 50051
    targetPort: 50051
---
apiVersion: v1
kind: Pod
metadata:
  name: timesrv-pod
  labels:
    name: timesrv-py-grpc
spec:
  containers:
  - name: my-timesrv
    image: time-grpc-app:local
    workingDir: /app
    ports:
    - containerPort: 50051
    command:
    - python3
    - "time_server.py"
       
