# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='time.proto',
  package='timeservice',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\ntime.proto\x12\x0btimeservice\" \n\x0bTimeRequest\x12\x11\n\trequestId\x18\x01 \x01(\x05\"\x1f\n\x0cTimeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2I\n\x04Time\x12\x41\n\x08WhatTime\x12\x18.timeservice.TimeRequest\x1a\x19.timeservice.TimeResponse\"\x00\x62\x06proto3'
)




_TIMEREQUEST = _descriptor.Descriptor(
  name='TimeRequest',
  full_name='timeservice.TimeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestId', full_name='timeservice.TimeRequest.requestId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=59,
)


_TIMERESPONSE = _descriptor.Descriptor(
  name='TimeResponse',
  full_name='timeservice.TimeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='timeservice.TimeResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['TimeRequest'] = _TIMEREQUEST
DESCRIPTOR.message_types_by_name['TimeResponse'] = _TIMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeRequest = _reflection.GeneratedProtocolMessageType('TimeRequest', (_message.Message,), {
  'DESCRIPTOR' : _TIMEREQUEST,
  '__module__' : 'time_pb2'
  # @@protoc_insertion_point(class_scope:timeservice.TimeRequest)
  })
_sym_db.RegisterMessage(TimeRequest)

TimeResponse = _reflection.GeneratedProtocolMessageType('TimeResponse', (_message.Message,), {
  'DESCRIPTOR' : _TIMERESPONSE,
  '__module__' : 'time_pb2'
  # @@protoc_insertion_point(class_scope:timeservice.TimeResponse)
  })
_sym_db.RegisterMessage(TimeResponse)



_TIME = _descriptor.ServiceDescriptor(
  name='Time',
  full_name='timeservice.Time',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=94,
  serialized_end=167,
  methods=[
  _descriptor.MethodDescriptor(
    name='WhatTime',
    full_name='timeservice.Time.WhatTime',
    index=0,
    containing_service=None,
    input_type=_TIMEREQUEST,
    output_type=_TIMERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TIME)

DESCRIPTOR.services_by_name['Time'] = _TIME

# @@protoc_insertion_point(module_scope)
